const {Bot,InlineKeyboard}=require('grammy'); const discord=require('./discord'); const cfg=require('./config');
const bot=new Bot(cfg.telegramToken);
function name(ctx){return [ctx.from?.first_name,ctx.from?.last_name].filter(Boolean).join(' ')||ctx.from?.username||'Telegram user';}
async function tgFile(ctx,fileId){const f=await ctx.api.getFile(fileId);return f.getUrl();}
async function media(ctx,msg){const a=[]; if(msg.photo?.length)a.push({url:await tgFile(ctx,msg.photo.at(-1).file_id),caption:msg.caption||''}); else if(msg.document)a.push({url:await tgFile(ctx,msg.document.file_id),caption:msg.caption||''}); else if(msg.video)a.push({url:await tgFile(ctx,msg.video.file_id),caption:msg.caption||''}); else if(msg.audio)a.push({url:await tgFile(ctx,msg.audio.file_id),caption:msg.caption||''}); else if(msg.voice)a.push({url:await tgFile(ctx,msg.voice.file_id),caption:msg.caption||''}); return a;}
async function open(ctx){const chatId=String(ctx.chat.id); const t=await discord.createTicket(chatId,name(ctx),ctx.message?.text||ctx.message?.caption||'(attachment)'); if(ctx.message){const files=await media(ctx,ctx.message); if(files.length) await discord.sendToThread(t,'',files);} await ctx.reply(`🎫 Ticket #${t.ticketNumber} opened.\n\nSend your messages here and support will reply in this chat.`,{reply_markup:new InlineKeyboard().text('🎫 Open Another Ticket','open')});}
bot.command('start',ctx=>ctx.reply('Welcome to Support!\n\nOpen a new ticket whenever you need help.',{reply_markup:new InlineKeyboard().text('🎫 Open Ticket','open')}));
bot.callbackQuery('open',async ctx=>{await ctx.answerCallbackQuery();await open(ctx);});
bot.on('message',async ctx=>{const t=discord.getActive(ctx.chat.id); if(!t){await ctx.reply('You do not have an active ticket.\n\nPress below to open a new one.',{reply_markup:new InlineKeyboard().text('🎫 Open Ticket','open')});return;} const text=ctx.message.text||ctx.message.caption||''; const files=await media(ctx,ctx.message); await discord.sendToThread(t,text,files);});
discord.client.on('staffReply',async({ticket,message})=>{try{if(message.content){for(const c of split(message.content))await bot.api.sendMessage(ticket.chatId,`💬 Support:\n${c}`);}for(const a of message.attachments.values()){await bot.api.sendDocument(ticket.chatId,a.url,{caption:'📎 Attachment from support'}).catch(()=>bot.api.sendMessage(ticket.chatId,`📎 Support attachment: ${a.url}`));}}catch(e){console.error('Staff reply:',e);}});
discord.client.on('ticketClosed',async t=>{await bot.api.sendMessage(t.chatId,'🔒 Your support ticket has been closed.\n\nIf you need help again, open a new ticket.',{reply_markup:new InlineKeyboard().text('🎫 Open New Ticket','open')}).catch(()=>{});});
function split(s){const a=[];while(s.length>cfg.maxLen){let i=s.lastIndexOf('\n',cfg.maxLen);if(i<500)i=s.lastIndexOf(' ',cfg.maxLen);if(i<1)i=cfg.maxLen;a.push(s.slice(0,i));s=s.slice(i).trimStart();}if(s)a.push(s);return a;}
(async()=>{await discord.start();bot.catch(e=>console.error('Telegram:',e));await bot.start();console.log('Telegram: running');})().catch(e=>{console.error(e);process.exit(1);});
